language: php

#addons:
  #chrome: stable
  #apt:
  #  packages:
  #    - nginx

sudo: false

#dist trusty, test fail on xenial, need find root cause
#dist: trusty

services:
  - mysql

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0

# Additional tests against stable PHP (min recommended version is 5.6) and past supported versions of WP
# and code coverage report.
#matrix:
  #fast_finish: true
  #include:
  #- php: 5.3
  #  dist: precise
  #- php: 5.2
  #  dist: precise
  #- name: "Coding standard check"
  #  php: 7.2
  #  env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1
  #- name: "e2e tests"
  #  php: 7.2
  #  env: WP_VERSION=latest WP_MULTISITE=0 RUN_E2E=1
  #- name: "Unit tests code coverage"
  #  php: 7.1
  #  env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
  #- name: "WooCommerce unit tests using WordPress nightly"
  #  php: 7.3
  #  env: WP_VERSION=nightly WP_MULTISITE=0
  #allow_failures:
  #- php: 7.1
  #  env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1

before_script:
  - |
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh woocommerce_test root '' 127.0.0.1 $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - bash tests/bin/phpunit.sh
  #- bash tests/bin/phpcs.sh
  #- travis_retry bash tests/bin/run-e2e-CI.sh

#after_script:
 # - bash tests/bin/travis.sh after

# Specifies that Travis should create builds for master and release branches and also tags.
#branches:
#  only:
#    - master
#    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
#    - /^release\//
